name: CD
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpunit --testdox --colors=always

  deploy:
    needs: [test]
    if: ${{ success() }}
    env:
      APP_ENV: prod
      APP_DEBUG: 0
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
            server: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            port: ${{ secrets.FTP_PORT }}
            server-dir: /www/tpchainedeprodR507/
            script: |
                cd /var/www/myapp
                git pull origin main
                composer install --no-scripts --no-dev
                php bin/console cache:clear