name: CD
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
        - name: Run tests
          run: echo "Running tests..."

        - run: composer install
        - run: php bin/phpunit
    
    deploy:
        needs: [test]
        if: github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Deploy to FTP Server
          uses: SamKirkland/FTP-Deploy-Action@v4.3.6
          with:
            server: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            port: ${{ secrets.FTP_PORT }}
            server-dir: /www/tpchainedeprodR507/
            script: |
                cd /var/www/myapp
                git pull origin main
                composer install --no-scripts --no-dev
                php bin/console cache:clear